/********************************************************************
* /d101/yjlee/pPbAna/AutoDict_vector_TH1D___cxx_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /d101/yjlee/pPbAna/AutoDict_vector_TH1D___cxx_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_inheritanceAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_typetableAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_memvarAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_globalAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_memfuncAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__cpp_setup_funcAutoDict_vector_TH1D___cxx_ACLiC_dict();
extern void G__set_cpp_environmentAutoDict_vector_TH1D___cxx_ACLiC_dict();
}


#include "/tmp/rootcint_F13RUk.h"
