// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/d101/yjlee/pPbAna/AutoDict_vector_TH1D__.cxx";

#endif
